### ISSUE TITLE
Mixture of ids provided via --input:  Please provide either SRA / ENA / DDBJ or Synapse ids!

### ISSUE THREAD

**Issue by royfrancis** [nf-core/fetchngs#116]
### Description of the bug

PRJNA625551 id is not recognised by the pipeline. Perhaps I am using it incorrectly.

### Command used and terminal output

```console
nextflow run nf-core/fetchngs --input PRJNA625551 --outdir results --input_type sra

ERROR: Validation of pipeline parameters failed!
* --input: string [PRJNA602995] does not match pattern ^\S+\.txt$ (PRJNA602995)
```

### System information

Nextflow/21.10.6
nf-core/2.1

**Comment by Midnighter** [comment]
The ID should be in a text file that you provide as input. Please try:

```bash
echo PRJNA625551 > ids.txt

nextflow run nf-core/fetchngs --input ids.txt --outdir results --input_type sra
```

**Comment by royfrancis** [comment]
Now I get this:

```
Mixture of ids provided via --input: 
Please provide either SRA / ENA / DDBJ or Synapse ids!
```

`nextflow run nf-core/fetchngs -c params.config`

params.config

```
params.input = "ids.txt"
params.outdir = "results"
params.input_type = "sra"

params.max_cpus = 10
params.max_memory = 64.GB 
params.max_time = 4.h

process {
    withName: SRATOOLS_PREFETCH {
        ext.args = '--max-size 60g'
    }
}

```

ids.txt

`PRJNA602995`

**Comment by Midnighter** [comment]
@drpatelh this is the same underlying issue as in #129. Did the NCBI eutils change? 🤔

**Comment by royfrancis** [comment]
Also getting the same error with SRR ids.

```
Mixture of ids provided via --input: 
Please provide either SRA / ENA / DDBJ or Synapse ids!
```

**ids.txt**
```
SRR16299658
```
**params.config**

```
params.input = "ids.txt"
params.outdir = "results"
params.input_type = "sra"

params.max_cpus = 10
params.max_memory = 64.GB 
params.max_time = 15.h
```

`nextflow run nf-core/fetchngs -c params.config -profile uppmax -resume --project snic2022-22-XXX`

```
Nextflow/22.10.1
nf-core/2.6
```

**Comment by onertipaday** [comment]
Same issue here with SRR.

> Mixture of ids provided via --input: 
> Please provide either SRA / ENA / DDBJ or Synapse ids!

**ids.txt**

> SRR8916053
> SRR8916054

**System Info**

> N E X T F L O W/ version 22.10.5 build 5840
> nf-core/fetchngs v1.9-g084e5ef

**Comment by drpatelh** [comment]
The id (`SRR16299658`) from [this comment](https://github.com/nf-core/fetchngs/issues/116#issuecomment-1435036089) works for me @royfrancis : 

```
[02/fce925] process > NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO (SRR16299658)             [100%] 1 of 1 ✔
[06/fa6ff4] process > NFCORE_FETCHNGS:SRA:SRA_RUNINFO_TO_FTP (1)                       [100%] 1 of 1 ✔
[b2/e4f24f] process > NFCORE_FETCHNGS:SRA:SRA_TO_SAMPLESHEET (SRX12578374_SRR16299658) [100%] 1 of 1 ✔
[0b/11faf1] process > NFCORE_FETCHNGS:SRA:SRA_MERGE_SAMPLESHEET                        [100%] 1 of 1 ✔
[6a/b19b80] process > NFCORE_FETCHNGS:SRA:MULTIQC_MAPPINGS_CONFIG                      [100%] 1 of 1 ✔
[e0/7b8500] process > NFCORE_FETCHNGS:SRA:CUSTOM_DUMPSOFTWAREVERSIONS (1)              [100%] 1 of 1 ✔
```

The ids (`SRR8916053`, `SRR8916054`) from [this comment]() work for me too @onertipaday:

```
[f9/f65fc8] process > NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO (SRR8916054)            [100%] 2 of 2 ✔
[f3/4cf125] process > NFCORE_FETCHNGS:SRA:SRA_RUNINFO_TO_FTP (2)                     [100%] 2 of 2 ✔
[7c/d1b381] process > NFCORE_FETCHNGS:SRA:SRA_TO_SAMPLESHEET (SRX5697508_SRR8916054) [100%] 2 of 2 ✔
[e0/5d0c57] process > NFCORE_FETCHNGS:SRA:SRA_MERGE_SAMPLESHEET                      [100%] 1 of 1 ✔
[4b/c47018] process > NFCORE_FETCHNGS:SRA:MULTIQC_MAPPINGS_CONFIG                    [100%] 1 of 1 ✔
[3e/26913d] process > NFCORE_FETCHNGS:SRA:CUSTOM_DUMPSOFTWAREVERSIONS (1)            [100%] 1 of 1 ✔
-[nf-core/fetchngs] Pipeline completed successfully-
```

Command I used:

```
nextflow run . \
    --input ids.txt \
    -profile docker \
    --skip_fastq_download \
    --outdir ./results \
```

Not sure why this was happening but it might be worth re-trying after we have released v1.10.0. If the problem persists please feel free to re-open or create a new issue if unrelated.

**Comment by amnahsiddiqa** [comment]
[ids_list.csv](https://github.com/nf-core/fetchngs/files/13845206/ids_list.csv)
Hi team- So I am still facing the same issue. I have my file attached here.  my command looks like this `nextflow run nf-core/fetchngs -c params.config -profile docker` And my error:`------------------------------------------------------
Mixture of ids provided via --input: SRR23679488
Please provide either SRA / ENA / GEO / DDBJ or Synapse ids!`
